"""Print the held-out evaluation report generated by training/train.py."""
from pathlib import Path
import json
ROOT = Path(__file__).resolve().parents[1]
report_path = ROOT / "artifacts" / "evaluation.json"
if not report_path.exists():
    raise SystemExit("No evaluation report found. Run python training/train.py first.")
report = json.loads(report_path.read_text(encoding="utf-8"))
print(json.dumps(report, indent=2))
print("\nInterpretation: accuracy alone is insufficient. Review false positives, false negatives, and performance on writing outside the training dataset.")
